name: CD for dev
on:
  workflow_dispatch:
    inputs:
      ws_image_tag:
        description: "Web service image tag"
        default: "latest-dev"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Hamo server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            export WS_IMAGE_TAG=${{ github.event.inputs.ws_image_tag }}
            cd /home/cpcuv2x/cpcuv2x/infra/dev-hamo
            git fetch --prune && git checkout --detach origin/dev
            docker-compose pull web-service
            docker-compose up -d
            docker image prune --force
