name: CD Web Service (Dev)
on:
  workflow_dispatch:
    inputs:
      ws_image_tag:
        description: "Web service image tag"
        default: "latest-dev"
        required: true
jobs:
  deploy-web-service:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Web Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            export WS_IMAGE_TAG=${{ github.event.inputs.ws_image_tag }}
            cd /home/cpcuv2x/cpcuv2x/infra/dev-hamo
            git fetch --prune && git checkout --detach origin/dev
            docker-compose pull web-service
            docker-compose up -d
            docker image prune --force
  migrate-dev:
    runs-on: ubuntu-latest
    needs: deploy-web-service
    steps:
      - name: Migrate PostgresDB
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/cpcuv2x/cpcuv2x/infra/dev-hamo
            git fetch --prune && git checkout --detach origin/dev
            docker-compose exec -T web-service pnpx prisma migrate dev
