name: Reset PostgresDB (Dev)
on:
  workflow_dispatch:
jobs:
  reset-postgresdb:
    runs-on: ubuntu-latest
    steps:
      - name: Reset PostgresDB
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/cpcuv2x/cpcuv2x/infra/dev-hamo
            git fetch --prune && git checkout --detach origin/dev
            docker-compose exec -T web-service pnpx prisma migrate reset --force
